DB_URL: jdbc:mysql://localhost:3306/vmall_user
DB_USERNAME: root
DB_PASSWORD: root
RABBIT_MQ_HOST: localhost
RABBIT_MQ_PORT: 5672
RABBIT_MQ_USER: guest
RABBIT_MQ_PASSWORD: guest
RABBIT_MQ_VIRTUAL_HOST: "/"
QUEUE_SEND_EMAIL_QUEUE_NAME: local.send.email.queue
QUEUE_SEND_EMAIL_EXCHANGE: local.send.email.exchange
QUEUE_SEND_EMAIL_ROUTING_KEY: local.send.email.routing-key

server:
  port: 8081
