spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASSWORD}
    virtual-host: ${RABBIT_MQ_VIRTUAL_HOST}

queue:
  send-email:
    queue-name: ${QUEUE_SEND_EMAIL_QUEUE_NAME}
    exchange: ${QUEUE_SEND_EMAIL_EXCHANGE}
    routing-key: ${QUEUE_SEND_EMAIL_ROUTING_KEY}
