spring:
#  Add a new schema.sql file in the src/main/resources folder
#  Initializing the database schema from an SQL script
#  sql:
#    init:
#      mode: always
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      The maximum time (ms) to spend waiting to get a connection from the pool
      connection-timeout: 2000
#      The maximum number of connections HikariCP will keep in the pool
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASSWORD}
    virtual-host: ${RABBIT_MQ_VIRTUAL_HOST}

queue:
  send-email:
    queue-name: ${QUEUE_SEND_EMAIL_QUEUE_NAME}
    exchange: ${QUEUE_SEND_EMAIL_EXCHANGE}
    routing-key: ${QUEUE_SEND_EMAIL_ROUTING_KEY}
  send-sms:
    queue-name: ${QUEUE_SEND_SMS_QUEUE_NAME}
    exchange: ${QUEUE_SEND_SMS_EXCHANGE}
    routing-key: ${QUEUE_SEND_SMS_ROUTING_KEY}
